# Generated by Django 5.0.4 on 2024-05-09 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedback_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='feedback',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1900, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
