name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:     
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: 'Create .env file'
        run: |
          touch .env
          echo POSTGRES_DB="${{ vars.POSTGRES_DB }}" >> .env
          echo POSTGRES_USER="${{ vars.POSTGRES_USER }}" >> .env
          echo POSTGRES_HOST="${{ vars.POSTGRES_HOST }}" >> .env
          echo DJANGO_DEBUG="${{ vars.DJANGO_DEBUG }}" >> .env
          echo DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" >> .env

      # Runs a single command using the runners shell
      - name: Run a makemigrations script
        run: docker-compose -f docker-compose.yml run web python company/manage.py makemigrations

      # Runs a single command using the runners shell
      - name: Run a migrate script
        run: docker-compose -f docker-compose.yml run web python company/manage.py migrate
  
      # Runs a single command using the runners shell
      - name: Run a test script for main app
        run: docker-compose -f docker-compose.yml run web python company/manage.py test main.tests
  
      # Runs a single command using the runners shell
      - name: Run a test script for services app
        run: docker-compose -f docker-compose.yml run web python company/manage.py test services.tests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 'Create .env file'
      run: |
        touch .env
        echo POSTGRES_DB="${{ vars.POSTGRES_DB }}" >> .env
        echo POSTGRES_USER="${{ vars.POSTGRES_USER }}" >> .env
        echo POSTGRES_HOST="${{ vars.POSTGRES_HOST }}" >> .env
        echo DJANGO_DEBUG="${{ vars.DJANGO_DEBUG }}" >> .env
        echo DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" >> .env
        echo POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" >> .env
    
    - uses: akhileshns/heroku-deploy@v3.12.12
      with: 
        heroku_api_key: ${{secrets.HEROKU_API_KEY}} 
        heroku_app_name: "knu-cicd-web-app-lab"
        heroku_email: "dmytrii_kolomarenko@knu.ua"
        env_file: ".env"
        usedocker: true
