name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    #- name: Install dependencies
      #run: |
        #python -m pip install --upgrade pip
        #pip install -r requirements.txt

    # Runs a single command using the runners shell
    - name: Run a makemigrations script
      run: docker-compose -f docker-compose.yml run web python company/manage.py makemigrations

    # Runs a single command using the runners shell
    - name: Run a migrate script
      run: docker-compose -f docker-compose.yml run web python company/manage.py migrate

    # Runs a single command using the runners shell
    - name: Run a test script for main app
      run: docker-compose -f docker-compose.yml run web python company/manage.py test main.tests

    # Runs a single command using the runners shell
    - name: Run a test script for services app
      run: docker-compose -f docker-compose.yml run web python company/manage.py test services.tests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a cicd_webapp_labs
        git push heroku main
