name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Runs a single command using the runners shell
    - name: Run a makemigrations script
      run: docker-compose -f docker-compose.yml run web python company/manage.py makemigrations

    # Runs a single command using the runners shell
    - name: Run a migrate script
      run: docker-compose -f docker-compose.yml run web python company/manage.py migrate

    # Runs a single command using the runners shell
    - name: Run a test script for main app
      run: docker-compose -f docker-compose.yml run web python company/manage.py test main.tests

    # Runs a single command using the runners shell
    - name: Run a test script for services app
      run: docker-compose -f docker-compose.yml run web python company/manage.py test services.tests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with: 
        heroku_api_key: ${{secrets.HEROKU_API_KEY}} 
        heroku_app_name: "knu-cicd-web-app-lab"
        heroku_email: "dmytrii_kolomarenko@knu.ua"

    
